#!/usr/bin/env python3
"""
Turns the Sunday School register export (SpreadsheetML ".xls", sheet
"User Completeness") into SQL that upserts the members table.

    python3 libs/db/scripts/members-from-register.py export.xls > members.sql
    python3 libs/db/scripts/members-from-register.py --fake 25 > sample.sql

The output contains personal data: write it outside the repos and delete it
after the import. Apply it with psql inside the database container, e.g.

    ssh ops@server 'sudo docker exec -i felege-db-production \\
      psql -U felege -d felege -v ON_ERROR_STOP=1' < members.sql

Rules:
- members.id is the number at the end of the member ID (ssu/01/03/05/00042 -> 42)
- re-running updates names, phone, email, type, gender and status, and never
  touches auth_user_id (existing account links stay)
- rows without a member ID are skipped and counted on stderr
- --fake N writes N made-up members (ids ssu/01/03/05/9xxxx) for staging

Standard library only (Python 3.8+).
"""
import random
import re
import sys
import xml.etree.ElementTree as ET

NS = "{urn:schemas-microsoft-com:office:spreadsheet}"
ID_RE = re.compile(r"^ssu/\d{2}/\d{2}/\d{2}/(\d{5})$", re.IGNORECASE)
GENDERS = {"ወንድ", "ሴት"}
TYPES = {"Regular", "Regular_Youth", "Special_Regular", "Honorary"}
COLUMNS = ["Custom ID", "Full Name", "First Name", "Last Name", "Email",
           "Phone Number", "Member Type", "Gender", "Member Status"]


def read_rows(path):
    root = ET.parse(path).getroot()
    rows = []
    for r in root.iter(NS + "Row"):
        vals = []
        for c in r.findall(NS + "Cell"):
            idx = c.get(NS + "Index")
            if idx:
                while len(vals) < int(idx) - 1:
                    vals.append("")
            d = c.find(NS + "Data")
            vals.append((d.text or "").strip() if d is not None else "")
        rows.append(vals)
    if not rows:
        sys.exit("No rows found. Is this the register export?")
    header = rows[0]
    missing = [c for c in COLUMNS if c not in header]
    if missing:
        sys.exit(f"Missing columns: {', '.join(missing)}")
    pos = {c: header.index(c) for c in COLUMNS}
    out = []
    for vals in rows[1:]:
        vals = vals + [""] * (len(header) - len(vals))
        out.append({c: vals[pos[c]] for c in COLUMNS})
    return out


def fake_rows(n):
    first = ["አበበ", "ሰላም", "ዮሐንስ", "ማርታ", "ሚካኤል", "ሄለን", "ዳዊት", "ቤተልሔም", "ናትናኤል", "ኤልሳቤጥ"]
    last = ["በቀለ", "ተስፋዬ", "ገብሩ", "ደስታ", "ኃይሉ", "ታደሰ", "አለሙ", "ወልዴ", "ሙሉጌታ", "ካሳ"]
    rnd = random.Random(42)
    rows = []
    for i in range(1, n + 1):
        f, l, g = rnd.choice(first), rnd.choice(last), rnd.choice(last)
        rows.append({
            "Custom ID": f"ssu/01/03/05/{90000 + i:05d}",
            "Full Name": f"{f} {l} {g}", "First Name": f, "Last Name": l,
            "Email": "", "Phone Number": f"+2519000{i:05d}",
            "Member Type": rnd.choice(sorted(TYPES - {"Honorary"})),
            "Gender": rnd.choice(sorted(GENDERS)), "Member Status": "Active",
        })
    return rows


def lit(v):
    return "NULL" if v is None or v == "" else "'" + v.replace("'", "''") + "'"


def to_sql(rows):
    values, skipped, seen = [], 0, {}
    for r in rows:
        mid = r["Custom ID"].strip()
        m = ID_RE.match(mid)
        if not m:
            skipped += 1
            continue
        num = int(m.group(1))
        if num in seen and seen[num] != mid.lower():
            sys.exit(f"Two member IDs map to id {num}: {seen[num]} and {mid}")
        if num in seen:
            skipped += 1
            continue
        seen[num] = mid.lower()
        first, last = r["First Name"].strip(), r["Last Name"].strip()
        words = r["Full Name"].split()
        grandfather = " ".join(words[2:]) if words[:2] == [first, last] and len(words) > 2 else None
        if not first or not last:
            skipped += 1
            continue
        mtype = r["Member Type"].strip()
        type_sql = f"(SELECT id FROM member_types WHERE name = {lit(mtype)})" if mtype in TYPES else "NULL"
        gender = r["Gender"].strip() if r["Gender"].strip() in GENDERS else None
        status = r["Member Status"].strip() or "Active"
        values.append(
            f"  ({num}, {lit(mid)}, {type_sql}, {lit(first)}, {lit(last)}, {lit(grandfather)}, "
            f"{lit(gender)}, {lit(status)}, {lit(r['Phone Number'].strip())}, {lit(r['Email'].strip())})"
        )
    if not values:
        sys.exit("No valid members found.")
    print(f"Members: {len(values)}, skipped: {skipped}", file=sys.stderr)
    return "\n".join([
        "-- Generated by libs/db/scripts/members-from-register.py. Contains personal data.",
        "BEGIN;",
        "INSERT INTO members (id, member_id, member_type_id, name, father_name, grandfather_name,",
        "  gender, status, address_phone, address_email) VALUES",
        ",\n".join(values),
        "ON CONFLICT (member_id) DO UPDATE SET",
        "  member_type_id = EXCLUDED.member_type_id, name = EXCLUDED.name,",
        "  father_name = EXCLUDED.father_name, grandfather_name = EXCLUDED.grandfather_name,",
        "  gender = EXCLUDED.gender, status = EXCLUDED.status,",
        "  address_phone = EXCLUDED.address_phone, address_email = EXCLUDED.address_email,",
        "  updated_at = now();",
        "SELECT count(*) AS members_total, count(auth_user_id) AS members_linked FROM members;",
        "COMMIT;",
        "",
    ])


def main(argv):
    if len(argv) == 3 and argv[1] == "--fake":
        rows = fake_rows(int(argv[2]))
    elif len(argv) == 2:
        rows = read_rows(argv[1])
    else:
        sys.exit(__doc__)
    sys.stdout.write(to_sql(rows))


if __name__ == "__main__":
    main(sys.argv)
