CREATE TABLE "attendance" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"event_id" uuid NOT NULL,
	"member_id" bigint NOT NULL,
	"status" text NOT NULL,
	"marked_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "attendance_event_id_member_id_key" UNIQUE("event_id","member_id"),
	CONSTRAINT "attendance_status_check" CHECK ("attendance"."status" in ('present', 'absent', 'late'))
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"emoji" text,
	"color" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "categories_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "departments" (
	"id" serial PRIMARY KEY NOT NULL,
	"name_en" text NOT NULL,
	"name_am" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "donations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"donor_id" uuid NOT NULL,
	"amount" numeric(10, 2) NOT NULL,
	"currency" text DEFAULT 'ETB',
	"payment_method" text,
	"receipt_url" text,
	"notes" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"verified_by" uuid,
	"verified_at" timestamp with time zone,
	"rejection_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "donations_payment_method_check" CHECK ("donations"."payment_method" in ('bank_transfer', 'telebirr', 'cash', 'other')),
	CONSTRAINT "donations_status_check" CHECK ("donations"."status" in ('pending', 'verified', 'rejected'))
);
--> statement-breakpoint
CREATE TABLE "events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"event_date" date NOT NULL,
	"start_time" time,
	"end_time" time,
	"department_id" integer,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"recurrence_group" uuid,
	"recurrence" text,
	"recurrence_until" date,
	CONSTRAINT "events_recurrence_check" CHECK ("events"."recurrence" is null or "events"."recurrence" in ('weekly', 'biweekly', 'monthly'))
);
--> statement-breakpoint
CREATE TABLE "members" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"member_id" text NOT NULL,
	"sunday_school_id" integer,
	"member_type_id" integer,
	"member_state" text,
	"status" text,
	"registration_date" text,
	"title" text,
	"name" text NOT NULL,
	"father_name" text,
	"grandfather_name" text,
	"mother_full_name" text,
	"god_name" text,
	"birth_date" text,
	"gender" text,
	"marital_status" text,
	"address_city" text,
	"address_sub_city" text,
	"address_phone" text,
	"address_email" text,
	"auth_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "members_member_id_unique" UNIQUE("member_id"),
	CONSTRAINT "members_auth_user_id_unique" UNIQUE("auth_user_id")
);
--> statement-breakpoint
CREATE TABLE "profiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"display_name" text,
	"full_name" text,
	"role" text DEFAULT 'member' NOT NULL,
	"department_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "profiles_role_check" CHECK ("profiles"."role" in ('member', 'dept_head', 'admin', 'super_admin'))
);
--> statement-breakpoint
CREATE TABLE "songs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"number" integer NOT NULL,
	"title" text NOT NULL,
	"title_en" text,
	"category" text NOT NULL,
	"lyrics" text NOT NULL,
	"audio_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "songs_number_unique" UNIQUE("number")
);
--> statement-breakpoint
ALTER TABLE "attendance" ADD CONSTRAINT "attendance_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attendance" ADD CONSTRAINT "attendance_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attendance" ADD CONSTRAINT "attendance_marked_by_profiles_id_fk" FOREIGN KEY ("marked_by") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "donations" ADD CONSTRAINT "donations_donor_id_profiles_id_fk" FOREIGN KEY ("donor_id") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "donations" ADD CONSTRAINT "donations_verified_by_profiles_id_fk" FOREIGN KEY ("verified_by") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_department_id_departments_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_created_by_profiles_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_department_id_departments_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "songs" ADD CONSTRAINT "songs_category_categories_name_fk" FOREIGN KEY ("category") REFERENCES "public"."categories"("name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_attendance_event_id" ON "attendance" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "idx_attendance_member_id" ON "attendance" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "idx_donations_donor_id" ON "donations" USING btree ("donor_id");--> statement-breakpoint
CREATE INDEX "idx_donations_status" ON "donations" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_events_department_id" ON "events" USING btree ("department_id");--> statement-breakpoint
CREATE INDEX "idx_events_date" ON "events" USING btree ("event_date" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_events_recurrence_group" ON "events" USING btree ("recurrence_group") WHERE "events"."recurrence_group" is not null;--> statement-breakpoint
CREATE INDEX "idx_members_auth_user_id" ON "members" USING btree ("auth_user_id");